#!/usr/bin/env ruby
require 'set'

list = ARGV.shift
if !list
  puts "Usage: wordlist filename"
  exit 1
end

db_file = list[/^([^\.]+)\..+$/,1] + '.set'

if File.exist? db_file
  puts "Deleting old database: #{db_file}"
  File.delete db_file
end

puts "Building index: #{db_file}"
index = Set.new

letter = nil
open(list, 'r') do |io|
  io.each_line do |word|
    if word[0] != letter
      print "#{word[0..0]} "; STDOUT.flush
      letter = word[0]
    end
  
    word = word.chomp.downcase
    index << word
  end
end

puts "Serializing index..."
open(db_file,'w') do |io|
  Marshal.dump(index, io)
end

puts "Done"